#include "startup.h"

vector_table_t vector_table __attribute__((section(".vectors"), aligned(2))) =
    {
        .stackTop = &__StackTop,
        .reset = Reset_Handler,
        .nmi = NMI_Handler,
        .hardFault = HardFault_Handler,
        .memManageFault = MemManage_Handler,
        .busFault = BusFault_Handler,
        .usageFault = UsageFault_Handler,
        .svCall = SVC_Handler,
        .debugMonitor = DebugMon_Handler,
        .pendSV = PendSV_Handler,
        .sysTick = SysTick_Handler,

        .irqs = {
            IRQ000_Handler,
            IRQ001_Handler,
            IRQ002_Handler,
            IRQ003_Handler,
            IRQ004_Handler,
            IRQ005_Handler,
            IRQ006_Handler,
            IRQ007_Handler,
            IRQ008_Handler,
            IRQ009_Handler,
            IRQ010_Handler,
            IRQ011_Handler,
            IRQ012_Handler,
            IRQ013_Handler,
            IRQ014_Handler,
            IRQ015_Handler,
            IRQ016_Handler,
            IRQ017_Handler,
            IRQ018_Handler,
            IRQ019_Handler,
            IRQ020_Handler,
            IRQ021_Handler,
            IRQ022_Handler,
            IRQ023_Handler,
            IRQ024_Handler,
            IRQ025_Handler,
            IRQ026_Handler,
            IRQ027_Handler,
            IRQ028_Handler,
            IRQ029_Handler,
            IRQ030_Handler,
            IRQ031_Handler,
            IRQ032_Handler,
            IRQ033_Handler,
            IRQ034_Handler,
            IRQ035_Handler,
            IRQ036_Handler,
            IRQ037_Handler,
            IRQ038_Handler,
            IRQ039_Handler,
            IRQ040_Handler,
            IRQ041_Handler,
            IRQ042_Handler,
            IRQ043_Handler,
            IRQ044_Handler,
            IRQ045_Handler,
            IRQ046_Handler,
            IRQ047_Handler,
            IRQ048_Handler,
            IRQ049_Handler,
            IRQ050_Handler,
            IRQ051_Handler,
            IRQ052_Handler,
            IRQ053_Handler,
            IRQ054_Handler,
            IRQ055_Handler,
            IRQ056_Handler,
            IRQ057_Handler,
            IRQ058_Handler,
            IRQ059_Handler,
            IRQ060_Handler,
            IRQ061_Handler,
            IRQ062_Handler,
            IRQ063_Handler,
            IRQ064_Handler,
            IRQ065_Handler,
            IRQ066_Handler,
            IRQ067_Handler,
            IRQ068_Handler,
            IRQ069_Handler,
            IRQ070_Handler,
            IRQ071_Handler,
            IRQ072_Handler,
            IRQ073_Handler,
            IRQ074_Handler,
            IRQ075_Handler,
            IRQ076_Handler,
            IRQ077_Handler,
            IRQ078_Handler,
            IRQ079_Handler,
            IRQ080_Handler,
            IRQ081_Handler,
            IRQ082_Handler,
            IRQ083_Handler,
            IRQ084_Handler,
            IRQ085_Handler,
            IRQ086_Handler,
            IRQ087_Handler,
            IRQ088_Handler,
            IRQ089_Handler,
            IRQ090_Handler,
            IRQ091_Handler,
            IRQ092_Handler,
            IRQ093_Handler,
            IRQ094_Handler,
            IRQ095_Handler,
            IRQ096_Handler,
            IRQ097_Handler,
            IRQ098_Handler,
            IRQ099_Handler,
            IRQ100_Handler,
            IRQ101_Handler,
            IRQ102_Handler,
            IRQ103_Handler,
            IRQ104_Handler,
            IRQ105_Handler,
            IRQ106_Handler,
            IRQ107_Handler,
            IRQ108_Handler,
            IRQ109_Handler,
            IRQ110_Handler,
            IRQ111_Handler,
            IRQ112_Handler,
            IRQ113_Handler,
            IRQ114_Handler,
            IRQ115_Handler,
            IRQ116_Handler,
            IRQ117_Handler,
            IRQ118_Handler,
            IRQ119_Handler,
            IRQ120_Handler,
            IRQ121_Handler,
            IRQ122_Handler,
            IRQ123_Handler,
            IRQ124_Handler,
            IRQ125_Handler,
            IRQ126_Handler,
            IRQ127_Handler,
            IRQ128_Handler,
            IRQ129_Handler,
            IRQ130_Handler,
            IRQ131_Handler,
            IRQ132_Handler,
            IRQ133_Handler,
            IRQ134_Handler,
            IRQ135_Handler,
            IRQ136_Handler,
            IRQ137_Handler,
            IRQ138_Handler,
            IRQ139_Handler,
            IRQ140_Handler,
            IRQ141_Handler,
            IRQ142_Handler,
            IRQ143_Handler,
        },
};

static_assert(sizeof(irq_vector_t) == 4, "irq_vector_t must be 4 bytes");
static_assert(sizeof(uint32_t *) == 4, "uint32_t must be 4 bytes");
static_assert(sizeof(vector_table) == (16 + 144) * 4, "vector_table does not match expected size");
